apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookhub-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookhub-backend
  template:
    metadata:
      labels:
        app: bookhub-backend
    spec:
      containers:
      - name: backend
        image: bookhub-backend:latest
        imagePullPolicy: Never
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: bookhub-config
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: bookhub-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bookhub-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: bookhub-config
              key: DB_NAME
        ports:
        - containerPort: 5000
