apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookhub-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookhub-db
  template:
    metadata:
      labels:
        app: bookhub-db
    spec:
      containers:
      - name: mongo
        image: mongo:7.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: bookhub-secret
              key: DB_USER
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bookhub-secret
              key: DB_PASSWORD
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
      volumes:
      - name: mongo-storage
        emptyDir: {}
